// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  window.FirstCtrl = function($scope, $http) {
    return $scope.hello = "Hello World";
  };

  window.SecondCtrl = function($scope, $http) {
    return $scope.hello = "Hello World";
  };

}).call(this);
