// Generated by CoffeeScript 1.3.3
(function() {
  'use strict';

  window.angular.module('myApp.filters', []).filter('interpolate', [
    'version', function(version) {
      return function(text) {
        return String(text).replace(/\%VERSION\%/mg, version);
      };
    }
  ]).filter('checkmark', function() {
    return function(input) {
      return input != null ? input : {
        '\u2713': '\u2718'
      };
    };
  });

}).call(this);
